#!/usr/bin/env python3
"""Generate STONE YAML files from upstream or adapter scripts via sim2stone."""

from __future__ import annotations

import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
UPSTREAM_DIR = REPO_ROOT / "upstream" / "cantera" / "reactors"
ADAPTER_DIR = REPO_ROOT / "adapters"
OUTPUT_DIR = REPO_ROOT / "examples" / "cantera"

# (id, source script relative to repo root, default mechanism, reactor_net var)
_GENERATED: list[tuple[str, Path, str, str | None]] = [
    ("combustor", UPSTREAM_DIR / "combustor.py", "gri30.yaml", None),
    ("reactor2", UPSTREAM_DIR / "reactor2.py", "gri30.yaml", None),
    (
        "nanosecond_pulse_discharge",
        ADAPTER_DIR / "nanosecond_pulse_discharge.py",
        "example_data/methane-plasma-pavan-2023.yaml",
        None,
    ),
    ("mix1", UPSTREAM_DIR / "mix1.py", "gri30.yaml", None),
    ("reactor1", UPSTREAM_DIR / "reactor1.py", "h2o2.yaml", None),
    ("periodic_cstr", ADAPTER_DIR / "periodic_cstr.py", "h2o2.yaml", None),
    ("fuel_injection", ADAPTER_DIR / "fuel_injection.py", "nDodecane_Reitz.yaml", None),
]


def _header(command: str) -> str:
    return (
        f"# Generated by: {command}\n"
        f"# Source repository: https://github.com/Cantera/cantera\n"
        f"# Do not edit by hand; regenerate with scripts/generate_examples.py\n"
    )


def _cantera_env() -> dict[str, str]:
    import cantera as ct

    base = Path(ct.__file__).resolve().parent / "data"
    example = base / "example_data"
    parts: list[str] = []
    if example.is_dir():
        parts.append(str(example))
    parts.append(str(base))
    prev = os.environ.get("CANTERA_DATA", "").strip()
    if prev:
        parts.append(prev)
    return {**os.environ, "CANTERA_DATA": os.pathsep.join(parts)}


def main() -> int:
    """Run sim2stone for each generated example and write YAML under examples/cantera."""
    os.environ.update(_cantera_env())
    os.environ.setdefault("MPLBACKEND", "Agg")
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    from boulder.sim2stone_cli import main as sim2stone_main

    failures = 0
    for example_id, script, mechanism, var_name in _GENERATED:
        if not script.is_file():
            print(f"skip missing source: {script}", file=sys.stderr)
            continue
        out_yaml = OUTPUT_DIR / f"{example_id}.yaml"
        args = [
            str(script),
            "-o",
            str(out_yaml),
            "--mechanism",
            mechanism,
            "--no-comments",
        ]
        if var_name:
            args.extend(["--var", var_name])
        rc = sim2stone_main(args)
        if rc != 0:
            print(f"sim2stone failed for {example_id}", file=sys.stderr)
            failures += 1
            continue
        body = out_yaml.read_text(encoding="utf-8")
        command = "sim2stone " + " ".join(args)
        out_yaml.write_text(_header(command) + body, encoding="utf-8")
        print(f"generated {out_yaml.name}")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
