#!/usr/bin/env python3
"""Generate STONE YAML files from upstream or adapter scripts via sim2stone."""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
UPSTREAM_DIR = REPO_ROOT / "upstream" / "cantera" / "reactors"
ADAPTER_DIR = REPO_ROOT / "adapters"
OUTPUT_DIR = REPO_ROOT / "examples"

# (id, source script relative to repo root, default mechanism, reactor_net var)
_GENERATED: list[tuple[str, Path, str, str | None]] = [
    ("combustor", ADAPTER_DIR / "combustor.py", "gri30.yaml", "sim"),
    ("reactor2", ADAPTER_DIR / "reactor2.py", "gri30.yaml", None),
    (
        "nanosecond_pulse_discharge",
        ADAPTER_DIR / "nanosecond_pulse_discharge.py",
        "example_data/methane-plasma-pavan-2023.yaml",
        None,
    ),
    ("mix1", ADAPTER_DIR / "mix1.py", "gri30.yaml", "sim"),
    ("reactor1", ADAPTER_DIR / "reactor1.py", "h2o2.yaml", "sim"),
    ("periodic_cstr", ADAPTER_DIR / "periodic_cstr.py", "h2o2.yaml", None),
    ("fuel_injection", ADAPTER_DIR / "fuel_injection.py", "nDodecane_Reitz.yaml", None),
    ("continuous_reactor", ADAPTER_DIR / "continuous_reactor.py", "gri30.yaml", None),
    ("piston", ADAPTER_DIR / "piston.py", "gri30.yaml", None),
]


def _header(command: str, yaml_relpath: str) -> str:
    return (
        f"# Run with: boulder {yaml_relpath}\n"
        f"# Generated by: {command}\n"
        f"# Source repository: https://github.com/Cantera/cantera\n"
        f"# Do not edit by hand; regenerate with scripts/generate_examples.py\n"
    )


def _display_path(path: Path) -> str:
    """Repo-relative path for provenance headers (portable across machines)."""
    return path.resolve().relative_to(REPO_ROOT.parent).as_posix()


def _sim2stone_command(
    script: Path,
    out_yaml: Path,
    mechanism: str,
    var_name: str | None,
) -> str:
    parts = [
        "sim2stone",
        _display_path(script),
        "-o",
        _display_path(out_yaml),
        "--mechanism",
        mechanism,
        "--no-comments",
    ]
    if var_name:
        parts.extend(["--var", var_name])
    return " ".join(parts)


def _cantera_env() -> dict[str, str]:
    import cantera as ct

    base = Path(ct.__file__).resolve().parent / "data"
    example = base / "example_data"
    parts: list[str] = []
    if example.is_dir():
        parts.append(str(example))
    parts.append(str(base))
    # Vendored mechanisms missing from the conda distribution (e.g.
    # n-heptane-NUIG-2016.yaml) — parent of upstream/cantera/example_data/ so
    # the upstream scripts' "example_data/<name>.yaml" relative path resolves.
    parts.append(str(REPO_ROOT / "upstream" / "cantera"))
    prev = os.environ.get("CANTERA_DATA", "").strip()
    if prev:
        parts.append(prev)
    return {**os.environ, "CANTERA_DATA": os.pathsep.join(parts)}


def _postprocess_body(example_id: str, body: str) -> str:
    """Apply catalog-specific YAML fixes after sim2stone."""
    if example_id == "mix1":
        body = re.sub(
            r"- id: outlet\n  Reservoir:\n(?:    .+\n)+",
            "- id: outlet\n  OutletSink: {}\n",
            body,
        )
    if example_id == "combustor":
        body = re.sub(
            r"continuation:\n(?:# derived_via: ast_match\n)?(?:  .+\n)+",
            "",
            body,
        )
        body = body.replace(
            "    closure: residence_time\n    tau_s: '{{residence_time}}'",
            "    closure: residence_time\n    tau_s: 0.1",
        )
    if example_id == "nanosecond_pulse_discharge":
        body = re.sub(
            r"-\n# derived_via: ast_match\n  id: gaussian_EN\n  kind: Gaussian\n"
            r"  peak: ([^\n]+)\n  center: ([^\n]+)\n  fwhm: ([^\n]+)",
            r"-\n# derived_via: ast_match\n  id: gaussian_EN\n  Gaussian:\n"
            r"    peak: \1\n    center: \2\n    fwhm: \3",
            body,
        )
        # Boulder's default solver.atol (1e-8) treats the electron/ion mole
        # fractions this plasma pulse actually drives (~1e-11 to ~1e-8) as
        # "within tolerance" noise, so CVODES never resolves the ionization
        # at all -- the whole pulse silently integrates as a no-op. A much
        # tighter atol/rtol (same knob already used for continuous_reactor
        # below, and documented in STONE_SPECIFICATIONS.md for exactly this
        # purpose) reproduces the correct several-orders-of-magnitude growth
        # in e/O2+/N2+/etc. seen in the vendored upstream script.
        body = body.replace(
            "    reinitialize_between_chunks: true\n",
            "    reinitialize_between_chunks: true\n    atol: 1.0e-15\n    rtol: 1.0e-9\n",
        )
        # N2/O2/CH4 dominate by mole fraction and crowd out the plasma
        # chemistry the example is actually about; force the reaction
        # intermediates/charged species into the chart instead (see
        # https://cantera.org/dev/examples/python/reactors/plasma_ignition.html
        # -style plots, which plot exactly this species set).
        body = re.sub(
            r"(- id: ConstPressureReactor_0\n(?:.+\n)+?      composition: [^\n]+\n)",
            r"\1"
            "  plot_options:\n"
            "    hide_species: [N2, O2, CH4]\n"
            '    show_species: [e, O2+, N2+, H2O+, CH4+, O, "N2(A)", '
            '"N2(B)", "N2(C)", "N2(a\')", CH3, CO2, CO, H2O, H, OH]\n',
            body,
        )
    if example_id == "continuous_reactor":
        body = body.replace(
            "    closure: residence_time\n    tau_s: '{{residence_time}}'",
            "    closure: residence_time\n    tau_s: 2.0",
        )
        # Boulder's default solver.atol (1e-8) is too loose for this
        # IdealGasMoleReactor's absolute mole scale (~1e-5 m3 volume): the
        # advance_grid replay drifts to a wrong composition (or, in the
        # standalone downloaded script, hits CVODES step-underflow). A
        # tighter atol/rtol — same knob STONE_SPECIFICATIONS.md itself
        # documents for exactly this purpose — reproduces the correct
        # converged composition exactly.
        body = body.replace(
            "  solver:\n    kind: advance_grid\n    grid:\n",
            "  solver:\n    kind: advance_grid\n    atol: 1.0e-15\n    rtol: 1.0e-9\n    grid:\n",
        )
    if example_id == "fuel_injection":
        body = body.replace(
            "phases:\n  gas:\n    mechanism: nDodecane_Reitz.yaml\n",
            "phases:\n  gas:\n    mechanism: nDodecane_Reitz.yaml#nDodecane_IG\n",
        )
        body = body.replace(
            "settings: {}\n",
            "settings:\n  solver:\n    kind: advance_grid\n    grid: {start: 0.0, stop: 10.0, dt: 0.01}\n",
        )
        # n2 dominates the mixture by mole fraction and crowds out the PAH
        # soot-precursor chemistry the example is actually about; force those
        # species into the chart instead.
        body = re.sub(
            r"(- id: IdealGasReactor_0\n(?:.+\n)+?  mechanism: [^\n]+\n)",
            r"\1  plot_options:\n"
            r"    hide_species: [n2]\n"
            r"    show_species: [A1c2h, A1c2h3, A1, A2, A2r5, A3, A4]\n",
            body,
        )
    return body


def main() -> int:
    """Run sim2stone for each generated example and write YAML under examples/."""
    os.environ.update(_cantera_env())
    os.environ.setdefault("MPLBACKEND", "Agg")
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Cantera reads CANTERA_DATA once at first use (already triggered above by
    # ``import cantera`` inside ``_cantera_env()``), so the env var update above
    # has no effect in-process; register the vendored mechanism directory
    # directly via the runtime API instead.
    import cantera as ct

    ct.add_directory(str(REPO_ROOT / "upstream" / "cantera"))

    from boulder.sim2stone_cli import main as sim2stone_main

    failures = 0
    for example_id, script, mechanism, var_name in _GENERATED:
        if not script.is_file():
            print(f"skip missing source: {script}", file=sys.stderr)
            continue
        out_yaml = OUTPUT_DIR / f"{example_id}.yaml"
        args = [
            str(script),
            "-o",
            str(out_yaml),
            "--mechanism",
            mechanism,
            "--no-comments",
        ]
        if var_name:
            args.extend(["--var", var_name])
        rc = sim2stone_main(args)
        if rc != 0:
            print(f"sim2stone failed for {example_id}", file=sys.stderr)
            failures += 1
            continue
        body = _postprocess_body(example_id, out_yaml.read_text(encoding="utf-8"))
        command = _sim2stone_command(script, out_yaml, mechanism, var_name)
        yaml_relpath = out_yaml.resolve().relative_to(REPO_ROOT).as_posix()
        out_yaml.write_text(_header(command, yaml_relpath) + body, encoding="utf-8")
        print(f"generated {out_yaml.name}")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
